# Generated by Django 5.1 on 2024-09-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('earnings', models.FloatField(blank=True, null=True)),
                ('cash_only', models.FloatField(blank=True, null=True)),
                ('total_debt', models.FloatField(blank=True, null=True)),
                ('fixed_assets', models.IntegerField(blank=True, null=True)),
                ('total_equity', models.IntegerField(blank=True, null=True)),
                ('operating_pnl', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.IntegerField(blank=True, null=True)),
                ('current_liabilities', models.IntegerField(blank=True, null=True)),
                ('earnings_before_tax', models.IntegerField(blank=True, null=True)),
                ('cash_and_equivalents', models.IntegerField(blank=True, null=True)),
                ('total_cash_and_due_from_banks', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viz_historical_financials',
            },
        ),
        migrations.CreateModel(
            name='ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('ownership_name', models.CharField(max_length=200)),
                ('share_value', models.BigIntegerField()),
                ('share_amount', models.BigIntegerField()),
                ('share_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'viz_ownership',
            },
        ),
    ]
