# Generated by Django 4.2.16 on 2024-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_rename_current_liabilities_historicalfinancials_liabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pb', models.FloatField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('ps', models.FloatField(blank=True, null=True)),
                ('pb_peer_avg', models.FloatField(blank=True, null=True)),
                ('pe_peer_avg', models.FloatField(blank=True, null=True)),
                ('ps_peer_avg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viz_historical_valuation',
            },
        ),
        migrations.CreateModel(
            name='overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('listing_board', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_industry', models.CharField(blank=True, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.IntegerField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_num', models.IntegerField(blank=True, null=True)),
                ('listing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('last_close_price', models.IntegerField(blank=True, null=True)),
                ('latest_close_date', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_close_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'viz_overview',
            },
        ),
    ]
