# Generated by Django 4.2.16 on 2024-09-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_historical_valuation_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfinancials',
            name='gross_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfinancials',
            name='total_assets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
