# Generated by Django 4.2.16 on 2024-09-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0004_historicalfinancials_gross_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfinancials',
            old_name='liabilities',
            new_name='current_liabilities',
        ),
    ]
